### ISSUE TITLE
mom-0.6.3-1.el8 refuse to start without any useful comment

### ISSUE THREAD

**Issue by dercol1** [oVirt/mom#20]
In log since ovirt-4.53.1 I have this... but I cannot interpeter it

2022-10-27 11:44:16,951 - mom - INFO - MOM starting
2022-10-27 11:44:16,977 - mom.HostMonitor - INFO - Host Monitor starting
2022-10-27 11:44:16,977 - mom - INFO - hypervisor interface vdsmjsonrpcclient
2022-10-27 11:44:16,994 - mom.HostMonitor - INFO - HostMonitor is ready
2022-10-27 11:44:17,008 - mom.GuestManager - INFO - Guest Manager starting: multi-thread
2022-10-27 11:44:17,010 - mom.Policy - INFO - Loaded policy '00-defines'
2022-10-27 11:44:17,011 - mom - ERROR - Failed to initialize MOM threads
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/mom/__init__.py", line 35, in run
    host_monitor, guest_manager)
  File "/usr/lib/python3.6/site-packages/mom/PolicyEngine.py", line 42, in __init__
    self.load_policy()
  File "/usr/lib/python3.6/site-packages/mom/PolicyEngine.py", line 71, in load_policy
    read_policy(fname, name.split('.policy')[0])
  File "/usr/lib/python3.6/site-packages/mom/PolicyEngine.py", line 53, in read_policy
    return self.policy.set_policy(policy_name, policyStr)
  File "/usr/lib/python3.6/site-packages/mom/Policy/Policy.py", line 64, in set_policy
    self.code = get_code(Evaluator(), self._cat_policies())
  File "/usr/lib/python3.6/site-packages/mom/Policy/Parser.py", line 543, in get_code
    tokens = scanner.tokenize(string)
  File "/usr/lib/python3.6/site-packages/mom/Policy/Parser.py", line 72, in tokenize
    GenericScanner.tokenize(self, input)
  File "/usr/lib/python3.6/site-packages/mom/Policy/spark.py", line 78, in tokenize
    add_lines = self.index2func[i](groups[i], line)
TypeError: t_default() takes 2 positional arguments but 3 were given

**Comment by dercol1** [comment]
I see that there is a bugreport: https://bugzilla.redhat.com/show_bug.cgi?id=2137532

**Comment by mwperina** [comment]
This has already been fixed as a part of oVirt 4.5.3.1 async release:

https://lists.ovirt.org/archives/list/users@ovirt.org/message/TCGC54KIG7XIYNBO44WKKLCNZJQITWMO/
